[2021-03-23 17:01:00,407] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-24T00:00:56.700091+00:00 [queued]>
[2021-03-23 17:01:00,411] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-24T00:00:56.700091+00:00 [queued]>
[2021-03-23 17:01:00,411] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 17:01:00,411] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-23 17:01:00,411] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 17:01:00,417] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): PushDataToCloud> on 2021-03-24T00:00:56.700091+00:00
[2021-03-23 17:01:00,419] {standard_task_runner.py:52} INFO - Started process 42678 to run task
[2021-03-23 17:01:00,428] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'PushDataToCloud', '2021-03-24T00:00:56.700091+00:00', '--job-id', '76', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpm2tg2qbo', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmp0ya43umu']
[2021-03-23 17:01:00,429] {standard_task_runner.py:77} INFO - Job 76: Subtask PushDataToCloud
[2021-03-23 17:01:00,457] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-24T00:00:56.700091+00:00 [running]> on host prathyushas-mbp.home
[2021-03-23 17:01:00,478] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=PushDataToCloud
AIRFLOW_CTX_EXECUTION_DATE=2021-03-24T00:00:56.700091+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-24T00:00:56.700091+00:00
[2021-03-23 17:01:00,567] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-03-23 17:01:17,055] {logging_mixin.py:104} INFO - executed
[2021-03-23 17:01:17,055] {python.py:118} INFO - Done. Returned value was: None
[2021-03-23 17:01:17,059] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=EDGAR-Annotation-Pipeline, task_id=PushDataToCloud, execution_date=20210324T000056, start_date=20210324T000100, end_date=20210324T000117
[2021-03-23 17:01:17,074] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-23 17:01:17,122] {local_task_job.py:146} INFO - Task exited with return code 0
