[2021-03-23 19:45:46,288] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-24T02:45:26.724060+00:00 [queued]>
[2021-03-23 19:45:46,293] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-24T02:45:26.724060+00:00 [queued]>
[2021-03-23 19:45:46,294] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 19:45:46,294] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-23 19:45:46,294] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 19:45:46,300] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): DownloadDataFromCloud> on 2021-03-24T02:45:26.724060+00:00
[2021-03-23 19:45:46,303] {standard_task_runner.py:52} INFO - Started process 43823 to run task
[2021-03-23 19:45:46,311] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'DownloadDataFromCloud', '2021-03-24T02:45:26.724060+00:00', '--job-id', '89', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpsk7oi3aw', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpz_bxhlwm']
[2021-03-23 19:45:46,313] {standard_task_runner.py:77} INFO - Job 89: Subtask DownloadDataFromCloud
[2021-03-23 19:45:46,343] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-24T02:45:26.724060+00:00 [running]> on host prathyushas-mbp.home
[2021-03-23 19:45:46,364] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=DownloadDataFromCloud
AIRFLOW_CTX_EXECUTION_DATE=2021-03-24T02:45:26.724060+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-24T02:45:26.724060+00:00
[2021-03-23 19:45:46,403] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-03-23 19:50:44,830] {python.py:118} INFO - Done. Returned value was: None
[2021-03-23 19:50:44,837] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=EDGAR-Annotation-Pipeline, task_id=DownloadDataFromCloud, execution_date=20210324T024526, start_date=20210324T024546, end_date=20210324T025044
[2021-03-23 19:50:44,852] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-23 19:50:44,885] {local_task_job.py:146} INFO - Task exited with return code 0
