[2021-03-23 19:45:29,146] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-24T02:45:26.724060+00:00 [queued]>
[2021-03-23 19:45:29,154] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-24T02:45:26.724060+00:00 [queued]>
[2021-03-23 19:45:29,155] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 19:45:29,155] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-23 19:45:29,155] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 19:45:29,164] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): PushDataToCloud> on 2021-03-24T02:45:26.724060+00:00
[2021-03-23 19:45:29,167] {standard_task_runner.py:52} INFO - Started process 43816 to run task
[2021-03-23 19:45:29,175] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'PushDataToCloud', '2021-03-24T02:45:26.724060+00:00', '--job-id', '88', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpqa_0c072', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpo6wz1kk9']
[2021-03-23 19:45:29,176] {standard_task_runner.py:77} INFO - Job 88: Subtask PushDataToCloud
[2021-03-23 19:45:29,209] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-24T02:45:26.724060+00:00 [running]> on host prathyushas-mbp.home
[2021-03-23 19:45:29,231] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=PushDataToCloud
AIRFLOW_CTX_EXECUTION_DATE=2021-03-24T02:45:26.724060+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-24T02:45:26.724060+00:00
[2021-03-23 19:45:29,303] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-03-23 19:45:43,568] {logging_mixin.py:104} INFO - executed
[2021-03-23 19:45:43,569] {python.py:118} INFO - Done. Returned value was: None
[2021-03-23 19:45:43,573] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=EDGAR-Annotation-Pipeline, task_id=PushDataToCloud, execution_date=20210324T024526, start_date=20210324T024529, end_date=20210324T024543
[2021-03-23 19:45:43,590] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-23 19:45:43,624] {local_task_job.py:146} INFO - Task exited with return code 0
