[2021-03-22 21:02:21,336] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-23T04:02:17.231561+00:00 [queued]>
[2021-03-22 21:02:21,344] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-23T04:02:17.231561+00:00 [queued]>
[2021-03-22 21:02:21,344] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 21:02:21,344] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-22 21:02:21,344] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 21:02:21,350] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): PushDataToCloud> on 2021-03-23T04:02:17.231561+00:00
[2021-03-22 21:02:21,352] {standard_task_runner.py:52} INFO - Started process 28022 to run task
[2021-03-22 21:02:21,363] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'PushDataToCloud', '2021-03-23T04:02:17.231561+00:00', '--job-id', '34', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmph1i7mmgr', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpqu3_ixvz']
[2021-03-22 21:02:21,365] {standard_task_runner.py:77} INFO - Job 34: Subtask PushDataToCloud
[2021-03-22 21:02:21,398] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-23T04:02:17.231561+00:00 [running]> on host prathyushas-mbp.home
[2021-03-22 21:02:21,426] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=PushDataToCloud
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T04:02:17.231561+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T04:02:17.231561+00:00
[2021-03-22 21:02:21,427] {taskinstance.py:1455} ERROR - No section: 'main1'
Traceback (most recent call last):
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/dags/edgar_annotation.py", line 22, in s3_upload
    execute=files_upload_edgar()
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/dags/files_upload.py", line 9, in files_upload_edgar
    bucket = config.get('main1', 'bucket')
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main1'
[2021-03-22 21:02:21,437] {taskinstance.py:1496} INFO - Marking task as FAILED. dag_id=EDGAR-Annotation-Pipeline, task_id=PushDataToCloud, execution_date=20210323T040217, start_date=20210323T040221, end_date=20210323T040221
[2021-03-22 21:02:21,464] {local_task_job.py:146} INFO - Task exited with return code 1
