[2021-03-23 18:14:00,337] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Model-Training-Pipeline.GetData 2021-03-23T22:13:47.455672+00:00 [queued]>
[2021-03-23 18:14:00,344] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Model-Training-Pipeline.GetData 2021-03-23T22:13:47.455672+00:00 [queued]>
[2021-03-23 18:14:00,344] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 18:14:00,344] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-23 18:14:00,344] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 18:14:00,352] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): GetData> on 2021-03-23T22:13:47.455672+00:00
[2021-03-23 18:14:00,357] {standard_task_runner.py:52} INFO - Started process 10613 to run task
[2021-03-23 18:14:00,369] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Model-Training-Pipeline', 'GetData', '2021-03-23T22:13:47.455672+00:00', '--job-id', '16', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/train.py', '--cfg-path', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmpbl6kdech', '--error-file', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmpid6hs9yz']
[2021-03-23 18:14:00,372] {standard_task_runner.py:77} INFO - Job 16: Subtask GetData
[2021-03-23 18:14:00,415] {logging_mixin.py:104} INFO - Running <TaskInstance: Model-Training-Pipeline.GetData 2021-03-23T22:13:47.455672+00:00 [running]> on host 152.1.168.192.in-addr.arpa
[2021-03-23 18:14:00,458] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Model-Training-Pipeline
AIRFLOW_CTX_TASK_ID=GetData
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T22:13:47.455672+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T22:13:47.455672+00:00
[2021-03-23 18:14:00,621] {logging_mixin.py:104} INFO - inside if
[2021-03-23 18:14:00,622] {logging_mixin.py:104} INFO - edgar_download
[2021-03-23 18:14:07,691] {taskinstance.py:1455} ERROR - Error tokenizing data. C error: Expected 3 fields in line 33, saw 8
Traceback (most recent call last):
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/dags/train.py", line 46, in getData
    dataset = pd.read_csv("edgar_download/annotation.csv",index_col=0)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1951, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 3 fields in line 33, saw 8

[2021-03-23 18:14:07,704] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=Model-Training-Pipeline, task_id=GetData, execution_date=20210323T221347, start_date=20210323T221400, end_date=20210323T221407
[2021-03-23 18:14:07,770] {local_task_job.py:146} INFO - Task exited with return code 1
