[2021-03-24 00:04:24,755] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Model-Training-Pipeline.Getdata 2021-03-24T04:04:13.645541+00:00 [queued]>
[2021-03-24 00:04:24,762] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Model-Training-Pipeline.Getdata 2021-03-24T04:04:13.645541+00:00 [queued]>
[2021-03-24 00:04:24,762] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-24 00:04:24,762] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-24 00:04:24,762] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-24 00:04:24,772] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): Getdata> on 2021-03-24T04:04:13.645541+00:00
[2021-03-24 00:04:24,776] {standard_task_runner.py:52} INFO - Started process 17010 to run task
[2021-03-24 00:04:24,784] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Model-Training-Pipeline', 'Getdata', '2021-03-24T04:04:13.645541+00:00', '--job-id', '56', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/train.py', '--cfg-path', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmprw7ly1ky', '--error-file', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmp395vbyq7']
[2021-03-24 00:04:24,787] {standard_task_runner.py:77} INFO - Job 56: Subtask Getdata
[2021-03-24 00:04:24,826] {logging_mixin.py:104} INFO - Running <TaskInstance: Model-Training-Pipeline.Getdata 2021-03-24T04:04:13.645541+00:00 [running]> on host 152.1.168.192.in-addr.arpa
[2021-03-24 00:04:24,855] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Model-Training-Pipeline
AIRFLOW_CTX_TASK_ID=Getdata
AIRFLOW_CTX_EXECUTION_DATE=2021-03-24T04:04:13.645541+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-24T04:04:13.645541+00:00
[2021-03-24 00:04:25,012] {logging_mixin.py:104} INFO - inside if
[2021-03-24 00:04:25,012] {logging_mixin.py:104} INFO - edgar_download
[2021-03-24 00:04:25,535] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: 'os.path.join(directory,filename)'
Traceback (most recent call last):
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/dags/train.py", line 51, in getData
    dataset = pd.read_csv('os.path.join(directory,filename)')
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/pandas/io/parsers.py", line 1368, in _open_handles
    storage_options=kwds.get("storage_options", None),
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/pandas/io/common.py", line 647, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'os.path.join(directory,filename)'
[2021-03-24 00:04:25,545] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=Model-Training-Pipeline, task_id=Getdata, execution_date=20210324T040413, start_date=20210324T040424, end_date=20210324T040425
[2021-03-24 00:04:25,606] {local_task_job.py:146} INFO - Task exited with return code 1
