[2021-03-22 20:57:13,793] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-23T03:57:09.744717+00:00 [queued]>
[2021-03-22 20:57:13,817] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-23T03:57:09.744717+00:00 [queued]>
[2021-03-22 20:57:13,817] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 20:57:13,817] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-22 20:57:13,817] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 20:57:13,825] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): PushDataToCloud> on 2021-03-23T03:57:09.744717+00:00
[2021-03-22 20:57:13,828] {standard_task_runner.py:52} INFO - Started process 27687 to run task
[2021-03-22 20:57:13,835] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'PushDataToCloud', '2021-03-23T03:57:09.744717+00:00', '--job-id', '32', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpeeblyd93', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpovpfjfgx']
[2021-03-22 20:57:13,838] {standard_task_runner.py:77} INFO - Job 32: Subtask PushDataToCloud
[2021-03-22 20:57:13,875] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-23T03:57:09.744717+00:00 [running]> on host prathyushas-mbp.home
[2021-03-22 20:57:13,898] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=PushDataToCloud
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T03:57:09.744717+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T03:57:09.744717+00:00
[2021-03-22 20:57:13,899] {taskinstance.py:1455} ERROR - No section: 'main1'
Traceback (most recent call last):
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/dags/edgar_annotation.py", line 22, in s3_upload
    execute=files_upload_edgar()
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/dags/files_upload.py", line 9, in files_upload_edgar
    bucket = config.get('main1', 'bucket')
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main1'
[2021-03-22 20:57:13,908] {taskinstance.py:1496} INFO - Marking task as FAILED. dag_id=EDGAR-Annotation-Pipeline, task_id=PushDataToCloud, execution_date=20210323T035709, start_date=20210323T035713, end_date=20210323T035713
[2021-03-22 20:57:13,934] {local_task_job.py:146} INFO - Task exited with return code 1
