[2021-03-23 18:33:32,602] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Model-Training-Pipeline.GetData 2021-03-23T22:33:22.325963+00:00 [queued]>
[2021-03-23 18:33:32,610] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Model-Training-Pipeline.GetData 2021-03-23T22:33:22.325963+00:00 [queued]>
[2021-03-23 18:33:32,610] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 18:33:32,610] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-23 18:33:32,610] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 18:33:32,619] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): GetData> on 2021-03-23T22:33:22.325963+00:00
[2021-03-23 18:33:32,623] {standard_task_runner.py:52} INFO - Started process 11610 to run task
[2021-03-23 18:33:32,650] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Model-Training-Pipeline', 'GetData', '2021-03-23T22:33:22.325963+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/train.py', '--cfg-path', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmpjlczt6pe', '--error-file', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmpxrhs3b4_']
[2021-03-23 18:33:32,655] {standard_task_runner.py:77} INFO - Job 21: Subtask GetData
[2021-03-23 18:33:32,719] {logging_mixin.py:104} INFO - Running <TaskInstance: Model-Training-Pipeline.GetData 2021-03-23T22:33:22.325963+00:00 [running]> on host 152.1.168.192.in-addr.arpa
[2021-03-23 18:33:32,757] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Model-Training-Pipeline
AIRFLOW_CTX_TASK_ID=GetData
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T22:33:22.325963+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T22:33:22.325963+00:00
[2021-03-23 18:33:32,957] {logging_mixin.py:104} INFO - inside if
[2021-03-23 18:33:32,958] {logging_mixin.py:104} INFO - edgar_download
[2021-03-23 18:33:33,356] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: 'edgar_download/annotation/annotation.csv.330E6BAC'
Traceback (most recent call last):
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/dags/train.py", line 45, in getData
    download()
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/dags/train.py", line 41, in download
    my_bucket.download_file(s3_object.key, os.path.join(directory,filename) )
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/boto3/s3/inject.py", line 246, in bucket_download_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/download.py", line 571, in _main
    fileobj.seek(offset)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/utils.py", line 367, in seek
    self._open_if_needed()
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/utils.py", line 350, in _open_if_needed
    self._fileobj = self._open_function(self._filename, self._mode)
  File "/Users/harika/Desktop/CSYE_7245/Assignment2/pipeline/MyEnv/lib/python3.7/site-packages/s3transfer/utils.py", line 261, in open
    return open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'edgar_download/annotation/annotation.csv.330E6BAC'
[2021-03-23 18:33:33,374] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=Model-Training-Pipeline, task_id=GetData, execution_date=20210323T223322, start_date=20210323T223332, end_date=20210323T223333
[2021-03-23 18:33:33,414] {local_task_job.py:146} INFO - Task exited with return code 1
