[2021-03-22 23:52:59,055] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-23T06:52:35.606345+00:00 [queued]>
[2021-03-22 23:52:59,062] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-23T06:52:35.606345+00:00 [queued]>
[2021-03-22 23:52:59,063] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 23:52:59,063] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-22 23:52:59,063] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 23:52:59,070] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): DownloadDataFromCloud> on 2021-03-23T06:52:35.606345+00:00
[2021-03-22 23:52:59,072] {standard_task_runner.py:52} INFO - Started process 36106 to run task
[2021-03-22 23:52:59,082] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'DownloadDataFromCloud', '2021-03-23T06:52:35.606345+00:00', '--job-id', '52', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpwkzhvkc7', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpc14n9xrm']
[2021-03-22 23:52:59,084] {standard_task_runner.py:77} INFO - Job 52: Subtask DownloadDataFromCloud
[2021-03-22 23:52:59,127] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-23T06:52:35.606345+00:00 [running]> on host prathyushas-mbp.home
[2021-03-22 23:52:59,161] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=DownloadDataFromCloud
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T06:52:35.606345+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T06:52:35.606345+00:00
[2021-03-22 23:52:59,236] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-03-22 23:52:59,364] {taskinstance.py:1455} ERROR - No option 'downloadpath' in section: 'main1'
Traceback (most recent call last):
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'downloadpath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/dags/edgar_annotation.py", line 37, in download
    parent_dir = config.get('main1', 'downloadpath')
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'downloadpath' in section: 'main1'
[2021-03-22 23:52:59,387] {taskinstance.py:1496} INFO - Marking task as FAILED. dag_id=EDGAR-Annotation-Pipeline, task_id=DownloadDataFromCloud, execution_date=20210323T065235, start_date=20210323T065259, end_date=20210323T065259
[2021-03-22 23:52:59,430] {local_task_job.py:146} INFO - Task exited with return code 1
