[2021-03-23 16:15:35,281] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-23T23:15:11.473084+00:00 [queued]>
[2021-03-23 16:15:35,286] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-23T23:15:11.473084+00:00 [queued]>
[2021-03-23 16:15:35,286] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 16:15:35,286] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-23 16:15:35,286] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 16:15:35,292] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): DownloadDataFromCloud> on 2021-03-23T23:15:11.473084+00:00
[2021-03-23 16:15:35,295] {standard_task_runner.py:52} INFO - Started process 41512 to run task
[2021-03-23 16:15:35,304] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'DownloadDataFromCloud', '2021-03-23T23:15:11.473084+00:00', '--job-id', '70', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpz7dlfee_', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmp_b1jm4jq']
[2021-03-23 16:15:35,306] {standard_task_runner.py:77} INFO - Job 70: Subtask DownloadDataFromCloud
[2021-03-23 16:15:35,335] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.DownloadDataFromCloud 2021-03-23T23:15:11.473084+00:00 [running]> on host prathyushas-mbp.home
[2021-03-23 16:15:35,357] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=DownloadDataFromCloud
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T23:15:11.473084+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T23:15:11.473084+00:00
[2021-03-23 16:15:35,398] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-03-23 16:15:48,443] {python.py:118} INFO - Done. Returned value was: None
[2021-03-23 16:15:48,447] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=EDGAR-Annotation-Pipeline, task_id=DownloadDataFromCloud, execution_date=20210323T231511, start_date=20210323T231535, end_date=20210323T231548
[2021-03-23 16:15:48,467] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-23 16:15:48,519] {local_task_job.py:146} INFO - Task exited with return code 0
