[2021-03-23 20:00:43,505] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.preprocess 2021-03-24T02:55:26.000664+00:00 [queued]>
[2021-03-23 20:00:43,510] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.preprocess 2021-03-24T02:55:26.000664+00:00 [queued]>
[2021-03-23 20:00:43,510] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 20:00:43,510] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-23 20:00:43,510] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 20:00:43,517] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): preprocess> on 2021-03-24T02:55:26.000664+00:00
[2021-03-23 20:00:43,520] {standard_task_runner.py:52} INFO - Started process 44239 to run task
[2021-03-23 20:00:43,527] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'preprocess', '2021-03-24T02:55:26.000664+00:00', '--job-id', '93', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpadegywgw', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpetzeh4ew']
[2021-03-23 20:00:43,529] {standard_task_runner.py:77} INFO - Job 93: Subtask preprocess
[2021-03-23 20:00:43,558] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.preprocess 2021-03-24T02:55:26.000664+00:00 [running]> on host prathyushas-mbp.home
[2021-03-23 20:00:43,579] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=preprocess
AIRFLOW_CTX_EXECUTION_DATE=2021-03-24T02:55:26.000664+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-24T02:55:26.000664+00:00
[2021-03-23 20:00:45,112] {taskinstance.py:1455} ERROR - 'utf-8' codec can't decode byte 0xb7 in position 1: invalid start byte
Traceback (most recent call last):
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/edgar_env/lib/python3.8/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/dags/edgar_annotation.py", line 79, in preprocess
    string = open(os.path.join(DIR,'{}'.format(i)),encoding='utf-8').read()
  File "/Users/prathyusha/opt/anaconda3/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 1: invalid start byte
[2021-03-23 20:00:45,513] {taskinstance.py:1496} INFO - Marking task as FAILED. dag_id=EDGAR-Annotation-Pipeline, task_id=preprocess, execution_date=20210324T025526, start_date=20210324T030043, end_date=20210324T030045
[2021-03-23 20:00:45,621] {local_task_job.py:146} INFO - Task exited with return code 1
