[2021-03-23 20:28:27,517] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-24T03:15:58.972660+00:00 [queued]>
[2021-03-23 20:28:27,522] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-24T03:15:58.972660+00:00 [queued]>
[2021-03-23 20:28:27,522] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 20:28:27,522] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-23 20:28:27,522] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 20:28:27,529] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): PushDataToCloud> on 2021-03-24T03:15:58.972660+00:00
[2021-03-23 20:28:27,531] {standard_task_runner.py:52} INFO - Started process 45886 to run task
[2021-03-23 20:28:27,540] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EDGAR-Annotation-Pipeline', 'PushDataToCloud', '2021-03-24T03:15:58.972660+00:00', '--job-id', '97', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/edgar_annotation.py', '--cfg-path', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmpz6ji8ynr', '--error-file', '/var/folders/_j/s8vbc0cs1fvgclq8hnvtq1wm0000gn/T/tmp8swn6fbb']
[2021-03-23 20:28:27,548] {standard_task_runner.py:77} INFO - Job 97: Subtask PushDataToCloud
[2021-03-23 20:28:27,593] {logging_mixin.py:104} INFO - Running <TaskInstance: EDGAR-Annotation-Pipeline.PushDataToCloud 2021-03-24T03:15:58.972660+00:00 [running]> on host prathyushas-mbp.home
[2021-03-23 20:28:27,630] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EDGAR-Annotation-Pipeline
AIRFLOW_CTX_TASK_ID=PushDataToCloud
AIRFLOW_CTX_EXECUTION_DATE=2021-03-24T03:15:58.972660+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-24T03:15:58.972660+00:00
[2021-03-23 20:28:27,732] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-03-23 20:28:48,515] {logging_mixin.py:104} INFO - executed
[2021-03-23 20:28:48,516] {python.py:118} INFO - Done. Returned value was: None
[2021-03-23 20:28:48,521] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=EDGAR-Annotation-Pipeline, task_id=PushDataToCloud, execution_date=20210324T031558, start_date=20210324T032827, end_date=20210324T032848
[2021-03-23 20:28:48,540] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-23 20:28:48,579] {local_task_job.py:146} INFO - Task exited with return code 0
